language: python

sudo: false

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install coveralls flake8 -e .

before_script:
  - flake8 --ignore=E501 mattermost_gitlab tests

script:
  - coverage run --source=mattermost_gitlab,tests tests/test.py

after_success:
  - coveralls --verbose
